<div class="modal-body">
Enter the security code generated by your authenticator app to make sure that it’s configured correctly.

<div class="col-12">
    <form id="setupGoogle2FAForm" method="POST" action="{{url('auth/two-factor/enable/google')}}">
        {{csrf_field()}}

        <div class="row">
            <div class="form-group">
                <label for="exampleSelect1">One time password:</label>
                <input name="otp" type="text" class="text-input-input" placeholder="6-digit code">
            </div>
        </div>
    </form>
</div>
</div>
<div class="modal-footer">
    <button type="button" id="setupGoogle2FABackToConfirm" class="btn btn-secondary">Back</button>
    <button type="button" id="setupGoogle2FASubmit" class="btn btn-primary">Submit</button>
</div>

<script>
    $('#setupGoogle2FABackToConfirm').on('click', function () {
        $('#setup2FAModal').find('.modal-loaded-content').load('/auth/two-factor/setup/1-ga-secret-key');
    });

    $('#setupGoogle2FASubmit').on('click', function () {
        $('#setupGoogle2FAForm').submit()
    });
</script>